# Generated by Django 4.0.4 on 2022-05-29 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receng', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('comedy', models.IntegerField()),
                ('drama', models.IntegerField()),
                ('fantasy', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('romance', models.IntegerField()),
                ('scifi', models.IntegerField()),
                ('thriller', models.IntegerField()),
                ('telugu', models.BooleanField()),
                ('hindi', models.BooleanField()),
                ('english', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
