# Generated by Django 4.0.4 on 2022-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receng', '0004_profile_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
